version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API Port
      - "9090:9090"  # MinIO Web UI Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - C:\MinIO\data:/data  # Windows Path for MinIO storage
    command: server /data --console-address ":9090"
